#Adding plugin for jekyll
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets

url: "https://smiths15.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap